### ISSUE TITLE
Can this be moved under the JuliaTraining directory please?

### ISSUE THREAD

**Issue by alanedelman** [JuliaComputing/JuliaBoxTutorials#25]

**Comment by logankilpatrick** [comment]
I don't see a "JuliaTraining" directory/repo anywhere @alanedelman @ViralBShah

**Comment by ViralBShah** [comment]
I think this repo is depended upon in various places. Can close this.

**Comment by NHDaly** [comment]
I assume that @alanedelman was referring to moving it under the https://github.com/JuliaTraining organization.

I'd also support renaming this repo so that it doesn't have JuliaBox in the title, since it is simply a collection of open-source tutorials for julia, contributed from the community, and isn't specific to JuliaBox. Whether we move it under the other organization seems less relevant to me.

Is that something we could still be open to? Regarding your concern about dependencies, I believe github automatically correctly handles forwarding repos after a rename.

**Comment by logankilpatrick** [comment]
Ah, makes sense. We could move to https://github.com/JuliaAcademy

**Comment by ViralBShah** [comment]
@aviks @mdpradeep Is this ok to do? Or is this repo hardcoded in JuliaBox?

**Comment by ViralBShah** [comment]
One possibility could be simply to make a copy in JuliaAcademy, and leave this one as is (if there are concerns about existing systems).
